version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    networks:
      - minio-net
    ports:
      - "9000:9000"
      - "9090:9090"
    command: [ "server", "/data", "--console-address", ":9090" ]
    environment:
      MINIO_CONFIG_ENV_FILE: /run/secrets/dyel_riot_and_minio_secrets
    secrets:
      - dyel_riot_and_minio_secrets

secrets:
  dyel_riot_and_minio_secrets:
    file: ./secrets/secrets.env

networks:
  # The presence of these objects is sufficient to define them
  minio-net: {}
