services:
  minio:
    image: quay.io/minio/minio
    networks:
      - minio-net
    ports:
      - "9000:9000"
      - "9090:9090"
    command: [ "server", "/data", "--console-address", ":9090" ]
    environment:
      MINIO_CONFIG_ENV_FILE: /run/secrets/secrets.env
    secrets:
      - minio_config

secrets:
  minio_config:
    file: ./secrets/minio_config.env

networks:
  # The presence of these objects is sufficient to define them
  minio-net: {}
